apps/urls.py
from django.urls import path
from apps import views

app_name = "apps"
urlpatterns = [
    path('', views.index, name='index'),
    path('add_album/', views.album_form, name='album_form'),
    path('add_musician/', views.musician_form, name='musician_form'),
    path('album_list/<int:artist_id>/', views.album_list, name='album_list'),
    path('edit_artist/<int:artist_id>/', views.edit_artist, name='edit_artist'),
    path('edit_album/<int:album_id>/', views.edit_album, name='edit_album'),
    path('delete_album/<int:album_id>/', views.delete_album, name='delete_album'),
    path('delete_artist/<int:artist_id>/', views.delete_musician, name='delete_musician'),
]

hello/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.urls')),

]

apps/models.py
from django.db import models


# Create your models here.
class Musician(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    instrument = models.CharField(max_length=100)

    def __str__(self):
        return self.first_name + " " + self.last_name


class Album(models.Model):
    artist = models.ForeignKey(Musician, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    release_date = models.DateField()
    rating = (
        (1, "Worst"),
        (2, "Bad"),
        (3, "Not Bad"),
        (4, "Good"),
        (5, "Excellent"),

    )
    num_stars = models.IntegerField(choices=rating)

    def __str__(self):
        return self.name + ", Rating: " + str(self.num_stars)

apps/forms.py
from django import forms
from django.core import validators
from apps.models import Musician, Album
from apps import models


class MusicianForm(forms.ModelForm):
    class Meta:
        model = models.Musician
        fields = "__all__"


class AlbumForm(forms.ModelForm):
    release_date = forms.DateField(widget=forms.TextInput(attrs=
                                                          {'type': 'date'}))

    class Meta:
        model = models.Album
        fields = "__all__"

apps/views.py
from django.shortcuts import render
from django.http import HttpResponse
from apps.models import Musician, Album
from apps import forms
from django.db.models import Avg, Max


# Create your views here.
def index(request):
    musician_list = Musician.objects.order_by('first_name')
    diction = {'title': "Home Page", 'musician_list': musician_list}
    return render(request, 'apps/index.html', context=diction)


def album_list(request, artist_id):
    artist_info = Musician.objects.get(pk=artist_id)
    album_list = Album.objects.filter(artist=artist_id).order_by('name')
    artist_rating = Album.objects.filter(artist=artist_id).aggregate(Avg('num_stars'))

    diction = {'title': "List of Albums", 'artist_info': artist_info, 'album_list': album_list,
               'artist_rating': artist_rating}
    return render(request, 'apps/album_list.html', context=diction)


def musician_form(request):
    form = forms.MusicianForm()

    if request.method == 'POST':
        form = forms.MusicianForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)

    diction = {'title': "Add Musician", 'musician_form': form}
    return render(request, 'apps/musician_form.html', context=diction)


def album_form(request):
    form = forms.AlbumForm()

    if request.method == 'POST':
        form = forms.AlbumForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)

    diction = {'title': "Add Album", 'album_form': form}
    return render(request, 'apps/album_form.html', context=diction)


def edit_artist(request, artist_id):
    artist_info = Musician.objects.get(pk=artist_id)
    form = forms.MusicianForm(instance=artist_info)

    if request.method == 'POST':
        form = forms.MusicianForm(request.POST, instance=artist_info)

        if form.is_valid():
            form.save(commit=True)
            return album_list(request, artist_id)

    diction = {'edit_form': form}
    return render(request, 'apps/edit_artist.html', context=diction)


def edit_album(request, album_id):
    album_info = Album.objects.get(pk=1)
    form = forms.AlbumForm(instance=album_info)
    diction = {}
    if request.method == 'POST':
        form = forms.AlbumForm(request.POST, instance=album_info)

        if form.is_valid():
            form.save(commit=True)
            diction.update({'success_text': 'Successfully Updated'})

    diction.update({'edit_form': form})
    diction.update({'album_id': album_id})
    return render(request, 'apps/edit_album.html', context=diction)


def delete_album(request, album_id):
    album = Album.objects.get(pk=album_id).delete()
    diction = {'delete_success': 'Album Deleted Successfully!!'}
    return render(request, 'apps/delete.html', context=diction)


def delete_musician(request, artist_id):
    artist = Musician.objects.get(pk=artist_id).delete(0)
    diction = {'delete_success': 'Musician Deleted Successfully!!'}

    return render(request, 'apps/delete.html', context=diction)

templates/apps/album_form.html
<!doctype html>
{% extends 'apps/base.html' %}
<!--inherit from the base-->

{% block body_block %}
<h3>Album Form</h3>
<form method="POST">
    {{ album_form.as_p }}
    {% csrf_token %}
    <input type="submit" name="submit" value="Add"
           class="btn btn-primary btn-small">
</form>

{% endblock %}

templates/apps/album_list.html
<!doctype html>
{% extends "apps/base.html" %}
<!--inherit from the base-->

{% block body_block %}
<h4>Artist Name: {{ artist_info.first_name }} {{ artist_info.last_name }} </h4>
<h4>Instrument: {{ artist_info.instrument }}</h4>
<h4>Artist Rating: {{ artist_rating.num_stars__avg }}</h4>
<a href="{% url 'apps:edit_artist' artist_id=artist_info.id %}" class="btn btn-success btn-sm">Edit</a>
<h3>Album List!!</h3>

<table class="table table-bordered">
    <tr>
        <th>Album Name</th>
        <th>Release Date</th>
        <th>Rating</th>

    </tr>
    {% for album in album_list %}
    <tr>
        <td><a href="{% url 'apps:edit_album' album_id=album.id  %}">{{ album.name }} </a> </td>
        <td>{{ album.release_date|date:"M d, Y" }}</td>
        <td>{{ album.num_stars }}</td>

    </tr>
    {% endfor %}

</table>

<br>

<a href="{% url 'apps:delete_musician' artist_id=artist_info.id %}" onclick="return confirm('Delete Musician?')" class="btn btn-danger btn-sm">Delete!!</a>

{% endblock %}

templates/apps/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
            integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"
            integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD"
            crossorigin="anonymous"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
            crossorigin="anonymous"></script>

    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>

<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <ul class="navbar-nav">
        <li class="nav-item active">
            <a href="{% url 'apps:index' %}">Home</a>
        </li>
        <li class="nav-item">
            <a href="{% url 'apps:musician_form' %}">Add Musician</a>
        </li>
        <li class="nav-item">
            <a href="{% url 'apps:album_form' %}">Add Album</a>
        </li>


    </ul>
</nav>

<div class="container">

    {% block body_block %}

    {% endblock %}

</div>

</body>
</html>

templates/apps/delete.html
<!doctype html>
{% extends "apps/base.html" %}
<!--inherit from the base-->

{% block body_block %}
<div class="alert alert-danger" > {{ delete_success }} </div>

{% endblock %}

templates/apps/edit_album.html
<!doctype html>
{% extends "apps/base.html" %}
<!--inherit from the base-->

{% block body_block %}

<h4>Edit Album!!</h4>
{% if success_text %}
<div class="alert alert-success">{{ success_text }}</div>
{% endif %}
<form method="POST">

    {{ edit_form.as_p }}
    {% csrf_token %}
    <input type="submit" name="submit" value="Update" class="btn btn-success btn-sm">

</form>
<br>
<a href="{% url 'apps:delete_album' album_id=album_id %}" class="btn btn-danger btn-sm" onclick="return confirm('delete this album?')">Deleted!!</a>

{% endblock %}

templates/apps/edit_artist.html
<!doctype html>
{% extends "apps/base.html" %}
<!--inherit from the base-->

{% block body_block %}
<h4>Edit Artist</h4>
<form method="POST">
    {{ edit_form.as_p }}
    {% csrf_token %}
    <input type="submit" name="submit" value="Update" class="btn btn-success btn-sm">

</form>

{% endblock %}

templates/apps/index.html
<!doctype html>
{% extends 'apps/base.html' %}
<!--inherit from the base-->

{% block body_block %}

<h3>List of Musicians</h3>

<ul>
    {% if musician_list %}
    {% for musician in musician_list %}
    <li><a href="{% url 'apps:album_list' artist_id=musician.id %}"> {{ musician.first_name }} {{ musician.last_name }}</a>
    </li>
    {% endfor %}
    {% else %}
    <h4>No Musician in the list</h4>
    {% endif %}


</ul>

{% endblock %}

templates/apps/musician_form.html
<!doctype html>
{% extends 'apps/base.html' %}
<!--inherit from the base-->

{% block body_block %}
<h3>Musician form!!</h3>
<form method="POST">
    {{ musician_form }}
    {% csrf_token %}
    <input type="submit" name="submit" value="Add"
           class="btn btn-primary btn-small">
</form>
{% endblock %}